### ISSUE TITLE
RF23HCEDBSR Refrigerator Support

### ISSUE THREAD

**Issue by rmackinnon** [kumy/samsung-ac-wifi-module#7]
Greetings, while looking into fix a dripping water filler on my Samsung Refrigerator, I found the wifi module you've been hacking on operating. Have you had a chance to test the pin row on the module edge (labeled 1-11) or the 14 pin pads on the back?  My hunch is that array of unpopulated pads is an ST 14 pin JTAG. Thoughts?  I'll update tomorrow with the model number. Wasn't aware my model came with a "connected" feature.

**Comment by kumy** [comment]
Hi @rmackinnon I also suppose the 14 pin rows is the JTAG port, and the 11 pin row the debug port as show in the schema found in the manual. I've tried to identify the hardware in this board without success yet, see https://electronics.stackexchange.com/questions/528747/what-is-this-mpu.

I've planned to explore the board internal once I've replaced it with my own (open) board. Until then I keep it safe in case of a rollback is needed.

**Please let me know here about your future findings, it promise to be very interesting!!!**

The project is at the moment stalled for some days as I'm waiting for the delivery of a level shifter. I have some code ready on my laptop. It's build over micropython and a pyboard D. I hope to have a first release in the next months.

**Comment by rmackinnon** [comment]
@kumy over all, the project sounds really exciting! Would be nice to have one more piece of hardware under house control, and not bleeding information.  I'm a python programmer too, and would be happy to help with what I can.  Especially testing.  I have a couple of micropython supported boards that I could use for testing.

Updated the issue title for reference, as this module exists there.  Seems as it is the Samsung "go-to" module for a class of IOT supported devices. I'll open this ticket back up once I have a lab setup and can start hacking on the feature set for the refrigerator and poking around on the JTAG and pins. :)  That linked diagram showing SD-card support...makes me wonder if that pin set on the edge has the pins for that.  I'll know more once I can poke at it.  Keep up the good work!
